name: blocker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #NETWORK
  dio: ^5.4.0
  # connectivity_plus: ^5.0.2

  #STATE
  flutter_bloc: ^8.1.3

  #UI
  go_router: ^13.0.0
  flutter_svg: ^2.0.9

  #TOOLS
  mask_text_input_formatter: ^2.7.0
  pin_code_fields: ^8.0.1
  permission_handler: ^11.3.0
  firebase_messaging: ^14.7.15
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  jwt_decoder: ^2.0.1
  webview_flutter: ^4.7.0
  # connectycube_flutter_call_kit: ^2.7.0
  # flutter_callkit_incoming: ^2.0.1+2
  # phone_state: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/navbar_icons/

  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400

